### ISSUE TITLE
Regarding signed assertions

### ISSUE THREAD

**Issue by broggeri** [privacycg/first-party-sets#11]
> Alternatively, the browser vendor, or some entities it designates, can sign assertions for domains which meet UA policy, using some private key.

From a site owner point of view, it sounds pretty bewildering that the browser vendor would define which of his web properties can be considered related or not. 

Wouldn't it make sense to look for a way to :
- map domains to a jurisdiction controller (of which they could be typically one per country and which would be under regulator control)
- have the jurisdiction controller attest of what domains are owner by the same legal entity AND do not confuse / hide to the users that the domains operate under a common umbrella.

In any case it makes no practical sense to have each useragent define its own rules as it just means that site owner will need to meet the superset of the rules necessary to cover (100 - epsilon) % of its traffic - whereas a per jurisdiction approach just means site owners will need to follow the rule of the jurisdiction they are registered to.

**Comment by davidben** [comment]
Thanks for the comments! Let me make sure I understand you correctly: It seems you are making two points, the first about overriding the site owner's declaration, and the second about interoperability across browsers.

These points apply equally to signed assertions and a static list. Signed assertions are just a static list with different deployment characteristics. (Imagine if the browser instead shipped a list of everything the signer signs.) I think this is really about the notion of UA policy itself.

The site owner's declaration is insufficient because we need to consider the user's interests (see the [Priority of Constituencies](https://www.w3.org/TR/html-design-principles/#priority-of-constituencies)). Two unrelated sites may want to join identities for tracking purposes, but that may not be what the user wants.

This is ultimately browser's role, hence "user agent". We do this throughout the web platform. For example:

* A site may want the user's location, but the browser may require some kind of permission prompt.
* A site may wish to play sound, but the browser may mute sites or control autoplay.
* The network may wish to intercept the user's communications, but browsers implement HTTPS.

These involve both technical mechanisms and UA-specific policies. There are APIs to request geolocation, but permissions UI is UA-specific. There are APIs for audio, but the controls and policies around it are UA-specific. HTTPS uses TLS, a standardized protocol, but OSs and UAs manage their own root programs to decide which keys are bound to which hostnames.

This explainer is primarily concerned with the technical mechanism itself, while the ideas you mention around jurisdiction are a possible input to the policy component.

Of course, the two parts need to work together. You're right that policy variations have interoperability impact. If all the UAs have wildly different requirements, it would be difficult to use first-party sets. We need to keep an eye on that. Hopefully, as with the other examples, first-party set policies will eventually converge. For now, [policies and privacy models](https://github.com/krgovind/first-party-sets#defining-acceptable-sets) in this space are still UA-specific, but there is work to define a [target privacy threat model](https://w3cping.github.io/privacy-threat-model/).

To that end, first-party sets does not fix on a particular policy so it can evolve as we understand the space better. The technical parts are designed to support that. Unlike TLS certificates and the Web PKI, a site can serve many assertions and the browser will ignore the ones it doesn't use. That allows a site to handle variations.

**Comment by johannhof** [comment]
I think it's reasonable to close this issue now as the current proposal is targeting a [common policy across user agents](https://github.com/privacycg/first-party-sets/blob/main/ua_policy_proposal.md#ua-policy-proposal) and places more agency and responsibility on site authors. Ultimately browsers will always have the power to restrict websites' capabilities based on their own judgement but such a step is not part of the current proposal.
